language: cpp

env:
  matrix:
    - COMPILER=g++-4.9
    - COMPILER=g++-4.8
    - COMPILER=g++-4.7

before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:boost-latest/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost1.54-dev libboost-program-options1.54-dev build-essential ${COMPILER}
 - wget http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz
 - tar xf cmake-3.2.2.tar.gz
 - cd cmake-3.2.2
 - ./configure
 - make
 - sudo make install
 - cd ..

before_script:
 - export CXX=${COMPILER}
 - mkdir build
 - cd build
 - cmake -DWITH_UNIT_TESTS=ON ..

script: make

after_script: make test
