language: cpp
sudo: false

matrix:
  include:
    - env:
        - COMPILER=g++-4.9
        - WITH_UNIT_TESTS=ON
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
      os: linux
    - env:
        - COMPILER=g++-4.8
        - WITH_UNIT_TESTS=ON
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - g++-4.8
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
      os: linux
    - env:
        - COMPILER=g++-4.7
        - WITH_UNIT_TESTS=ON
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - g++-4.7
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
      os: linux
    - env:
        - COMPILER=clang++-3.5
        - WITH_UNIT_TESTS=ON
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - clang-3.5
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
      os: linux
    - env:
        - COMPILER=clang++-3.6
        - WITH_UNIT_TESTS=ON
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
            - boost-latest
            - george-edison55-precise-backports
          packages:
            - clang-3.6
            - cmake
            - cmake-data
            - libboost1.55-dev
            - libboost-regex1.55-dev
            - libboost-program-options1.55-dev
      os: linux
    - env:
        - COMPILER=clang++
        - WITH_UNIT_TESTS=OFF
      os: osx

before_script:
 - export CXX=${COMPILER}
 - ${COMPILER} --version
 - mkdir build
 - cd build
 - cmake ..

script: make

after_script: make test
