language: cpp

sudo: false

env:
  matrix:
    - COMPILER=g++-4.9
    - COMPILER=g++-4.8
    - COMPILER=g++-4.7
    - COMPILER=clang++-3.5
    - COMPILER=clang++-3.6

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - boost-latest
     - llvm-toolchain-precise-3.5
     - llvm-toolchain-precise-3.6
     - llvm-toolchain-precise-3.7
     - george-edison55-precise-backports
    packages:
     - g++-4.7
     - g++-4.8
     - g++-4.9
     - clang-3.5
     - clang-3.6
     - build-essential
     - cmake
     - libboost1.55-dev
     - libboost-regex1.55-dev
     - libboost-program-options1.55-dev

before_script:
 - export CXX=${COMPILER}
 - mkdir build
 - cd build
 - cmake -DWITH_UNIT_TESTS=ON ..

script: make

after_script: make test
